-- ============================================================================
-- Spoken English — INTERACTION (Responsiveness) drill questions
-- ============================================================================
-- The one sub-skill missing SE-tagged drill rows. 12 BEGINNER + 12 INTERMEDIATE MCQs testing
-- conversational responsiveness (appropriate replies, follow-ups, turn-taking, agreeing/disagreeing,
-- back-channelling). Matches the DrillQuestion schema + the other 5 SE sub-skills (12 per level).
-- Idempotent via unique source_key. Run on the DB (dev = public):
--     psql "$DATABASE_URL" -f prisma/seeds/spoken_english_interaction_drills.sql
-- ============================================================================

INSERT INTO drill_questions
  (skill, sub_skill, level, drill_type, prompt_text, options, correct_answer, explanation, exam_id, is_active, source_key)
VALUES
  -- ─── BEGINNER (12) ─────────────────────────────────────────────────────
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','A friend says: "Hi, how are you?" What is the most natural reply?','{"A":"Yes.","B":"I''m good, thanks — and you?","C":"I am here.","D":"How are you too now."}'::jsonb,'"B"'::jsonb,'A good response answers AND returns the question, keeping the exchange going.','spoken_english',true,'drill_se_interaction_beg_001'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','Someone says: "Thank you so much for your help." What do you say?','{"A":"You''re welcome.","B":"Yes I helped.","C":"Thank you so much for your help.","D":"No thanks."}'::jsonb,'"A"'::jsonb,'"You''re welcome" is the standard, polite reply to thanks.','spoken_english',true,'drill_se_interaction_beg_002'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','A colleague says: "Sorry I''m late." The most polite response is:','{"A":"You are always late.","B":"That''s okay, no problem.","C":"Why?","D":"Sorry too."}'::jsonb,'"B"'::jsonb,'Accepting an apology graciously keeps the interaction friendly.','spoken_english',true,'drill_se_interaction_beg_003'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','Your friend says: "I just got a new job!" A good follow-up is:','{"A":"Okay.","B":"That''s great! Where will you be working?","C":"I have a job too.","D":"New job."}'::jsonb,'"B"'::jsonb,'Reacting positively and asking a follow-up question shows interest and continues the conversation.','spoken_english',true,'drill_se_interaction_beg_004'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','Someone invites you: "Would you like to join us for lunch?" A natural accept is:','{"A":"Maybe not now later.","B":"Sure, I''d love to. Thanks!","C":"Lunch is food.","D":"You like lunch?"}'::jsonb,'"B"'::jsonb,'A clear, warm acceptance with thanks is the responsive choice.','spoken_english',true,'drill_se_interaction_beg_005'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','You didn''t hear what someone said. The polite way to respond is:','{"A":"What?","B":"Say again.","C":"Sorry, could you repeat that, please?","D":"I don''t know."}'::jsonb,'"C"'::jsonb,'A polite request for repetition keeps the conversation going respectfully.','spoken_english',true,'drill_se_interaction_beg_006'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','Someone says: "I like your jacket." The best reply is:','{"A":"I know.","B":"Thanks! I got it last week.","C":"It is a jacket.","D":"Do you?"}'::jsonb,'"B"'::jsonb,'Accepting a compliment with thanks (and a small comment) is friendly and responsive.','spoken_english',true,'drill_se_interaction_beg_007'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','A person is telling a story. To show you are listening, you can say:','{"A":"(say nothing and look away)","B":"Oh really? Then what happened?","C":"Stop talking.","D":"I am busy."}'::jsonb,'"B"'::jsonb,'Small reactions and follow-up questions (back-channelling) signal active listening.','spoken_english',true,'drill_se_interaction_beg_008'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','Someone says: "Nice to meet you." You reply:','{"A":"Okay.","B":"Nice to meet you too.","C":"Yes I meet you.","D":"Meet."}'::jsonb,'"B"'::jsonb,'Mirroring the greeting warmly is the natural, responsive reply.','spoken_english',true,'drill_se_interaction_beg_009'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','You agree with what your friend said. A natural way to show it is:','{"A":"Yes, exactly! I think so too.","B":"No comment.","C":"Maybe you are wrong.","D":"I don''t care."}'::jsonb,'"A"'::jsonb,'Explicitly agreeing and adding "I think so too" keeps the exchange collaborative.','spoken_english',true,'drill_se_interaction_beg_010'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','You need to leave a conversation. The polite way to end it is:','{"A":"(walk away silently)","B":"It was great talking to you. See you soon!","C":"I go now bye.","D":"Stop."}'::jsonb,'"B"'::jsonb,'A warm closing line ends the interaction politely and leaves it open for next time.','spoken_english',true,'drill_se_interaction_beg_011'),
  ('SPEAKING','INTERACTION','BEGINNER','MCQ','A waiter asks: "Are you ready to order?" If you need a minute, you say:','{"A":"No.","B":"Could we have a few more minutes, please?","C":"Order now.","D":"I am ready no."}'::jsonb,'"B"'::jsonb,'Asking politely for more time responds clearly without being abrupt.','spoken_english',true,'drill_se_interaction_beg_012'),

  -- ─── INTERMEDIATE (12) ─────────────────────────────────────────────────
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','Your friend says: "I''ve been really stressed at work lately." The most responsive reply is:','{"A":"Everyone is stressed.","B":"That sounds tough — what''s been the hardest part?","C":"You should quit.","D":"Anyway, did you watch the game?"}'::jsonb,'"B"'::jsonb,'Acknowledging the feeling and inviting them to say more shows empathy and keeps the conversation open.','spoken_english',true,'drill_se_interaction_int_001'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','You disagree with a colleague''s idea in a meeting. The most tactful response is:','{"A":"That''s wrong.","B":"I see your point, but have we considered the cost side?","C":"No, my idea is better.","D":"Whatever you say."}'::jsonb,'"B"'::jsonb,'Acknowledging their view before raising a concern is the polite, collaborative way to disagree.','spoken_english',true,'drill_se_interaction_int_002'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','Someone shares bad news: "My flight got cancelled." A good response is:','{"A":"Oh no, that''s frustrating. Do you know when the next one is?","B":"That happens.","C":"You should have flown earlier.","D":"Okay."}'::jsonb,'"A"'::jsonb,'Expressing sympathy and asking a practical follow-up shows genuine engagement.','spoken_english',true,'drill_se_interaction_int_003'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','Two people are talking and you want to add something without being rude. You say:','{"A":"(interrupt loudly)","B":"Sorry to jump in — can I add something here?","C":"Listen to me now.","D":"You are both wrong."}'::jsonb,'"B"'::jsonb,'A brief, polite signal before contributing manages turn-taking smoothly.','spoken_english',true,'drill_se_interaction_int_004'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','A friend invites you out but you can''t go. The most considerate reply is:','{"A":"No.","B":"I''d love to, but I''ve already got plans — can we do it next week?","C":"I''m busy, don''t ask.","D":"Maybe."}'::jsonb,'"B"'::jsonb,'Softening the refusal and offering an alternative keeps the relationship warm.','spoken_english',true,'drill_se_interaction_int_005'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','To show you are actively listening and want more detail, you ask:','{"A":"So what made you decide to do that?","B":"Are you done?","C":"That''s enough about you.","D":"I already knew that."}'::jsonb,'"A"'::jsonb,'An open follow-up question invites elaboration and signals real interest.','spoken_english',true,'drill_se_interaction_int_006'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','You didn''t fully understand a point. The best way to respond is:','{"A":"You''re not making sense.","B":"Just to make sure I follow — do you mean we start on Monday?","C":"Never mind.","D":"Okay okay."}'::jsonb,'"B"'::jsonb,'Checking understanding by paraphrasing keeps the conversation clear and collaborative.','spoken_english',true,'drill_se_interaction_int_007'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','The conversation has paused and you want to change the topic smoothly. You say:','{"A":"That reminds me — how did your project turn out?","B":"Boring. New topic.","C":"Let''s stop talking about this.","D":"(long silence)"}'::jsonb,'"A"'::jsonb,'Linking to a new topic with "that reminds me" keeps the flow natural rather than abrupt.','spoken_english',true,'drill_se_interaction_int_008'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','A colleague suggests an approach you''re unsure about. A responsive, open reply is:','{"A":"That won''t work.","B":"That could work — what would we do if the client says no?","C":"Fine, do it.","D":"I don''t like it."}'::jsonb,'"B"'::jsonb,'Showing openness while probing a risk keeps the dialogue constructive.','spoken_english',true,'drill_se_interaction_int_009'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','Your friend excitedly tells you they passed an exam. Matching their energy, you say:','{"A":"Congratulations! You must be so relieved — how did you celebrate?","B":"Good for you.","C":"Exams are easy.","D":"Okay, cool."}'::jsonb,'"A"'::jsonb,'Matching the speaker''s enthusiasm and asking a follow-up strengthens the connection.','spoken_english',true,'drill_se_interaction_int_010'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','Someone misunderstands what you meant. The best way to respond is:','{"A":"That''s not what I said, listen.","B":"Sorry, I didn''t explain that well — what I meant was...","C":"Forget it.","D":"You never understand."}'::jsonb,'"B"'::jsonb,'Taking shared responsibility and re-explaining calmly repairs the misunderstanding.','spoken_english',true,'drill_se_interaction_int_011'),
  ('SPEAKING','INTERACTION','INTERMEDIATE','MCQ','A quieter person in a group hasn''t spoken. To include them, you say:','{"A":"Why are you so quiet?","B":"What do you think, Priya? We''d love to hear your view.","C":"(ignore them)","D":"Only we will decide."}'::jsonb,'"B"'::jsonb,'Inviting someone in by name and encouraging their input shows strong interactive skill.','spoken_english',true,'drill_se_interaction_int_012')
ON CONFLICT (source_key) DO NOTHING;
